CREATE  PROCEDURE [fpx].[usp_Uplift_Consumption_Tankering]
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID('[fpx].[Report_Uplift_Consumption_Tankering]', 'U') IS NULL
    BEGIN
        SELECT
              AF.[FlightID]                 AS [AF_FlightID]
            , AF.[FlightDate]               AS [AF_FlightDate]
            , CONCAT(YEAR(AF.[FlightDate]),' ',RIGHT('00' + CAST(DATEPART(WEEK, AF.[FlightDate]) AS VARCHAR(2)), 2)) AS WeeksLabel
            , CAST(YEAR(AF.[FlightDate]) AS INT) * 100 + DATEPART(WEEK, AF.[FlightDate]) AS WeekKey
            , AF.[Registration]             AS [AF_Registration]
            , AF.[Departure]                AS [AF_Departure]
            , AF.[Destination]              AS [AF_Destination]
            , AF.[AirlineDesignator]        AS [AF_AirlineDesignator]
            , AF.[FlightNumber]             AS [AF_FlightNumber]
            , AF.[Suffix]                   AS [AF_Suffix]
            , AF.[AircraftType]             AS [AF_AircraftType]
            , AF.[Leg]                      AS [AF_Leg]
            , AF.[LegAircraftType]          AS [AF_LegAircraftType]
            , AF.[SpecialEvent]             AS [AF_SpecialEvent]
            , AF.[DomInt]                   AS [AF_DomInt]
            , AF.[DepartureDate]            AS [AF_DepartureDate]
            , AF.[OffBlockTimeUTC]          AS [AF_OffBlockTimeUTC]
            , AF.[TakeOffTimeUTC]           AS [AF_TakeOffTimeUTC]
            , AF.[TouchDownTimeUTC]         AS [AF_TouchDownTimeUTC]
            , AF.[OnBlockTimeUTC]           AS [AF_OnBlockTimeUTC]
            , AF.[BlockTime]                AS [AF_BlockTime]
            , AF.[FlightTime]               AS [AF_FlightTime]
            , AF.[Operator]                 AS [AF_Operator]
            , AF.[Owner]                    AS [AF_Owner]
            , AF.[Customer]                 AS [AF_Customer]
            , AF.[UpliftVol]                AS [AF_UpliftVol]
            , AF.[UpliftMass]               AS [AF_UpliftMass]
            , AF.[UpliftDensity]            AS [AF_UpliftDensity]
            , AF.[UpliftStatus]             AS [AF_UpliftStatus]
            , AF.[UpliftCost]               AS [AF_UpliftCost]
            , AF.[IPStatus]                 AS [AF_IPStatus]
            , AF.[BeforeFuelingVol]         AS [AF_BeforeFuelingVol]
            , AF.[BeforeFuelingMass]        AS [AF_BeforeFuelingMass]
            , AF.[OffBlockFuelVol]          AS [AF_OffBlockFuelVol]
            , AF.[OffBlockFuelMass]         AS [AF_OffBlockFuelMass]
            , AF.[ShutDownFuelVol]          AS [AF_ShutDownFuelVol]
            , AF.[ShutDownFuelMass]         AS [AF_ShutDownFuelMass]
            , AF.[FuelDumpVol]              AS [AF_FuelDumpVol]
            , AF.[FuelDumpMass]             AS [AF_FuelDumpMass]
            , AF.[BlockConsumptionVol]      AS [AF_BlockConsumptionVol]
            , AF.[BlockConsumptionMass]     AS [AF_BlockConsumptionMass]
            , AF.[BlockConsumptionStatus]   AS [AF_BlockConsumptionStatus]
            , AF.[TotalConsumptionVol]      AS [AF_TotalConsumptionVol]
            , AF.[TotalConsumptionMass]     AS [AF_TotalConsumptionMass]
            , AF.[TotalConsumptionStatus]   AS [AF_TotalConsumptionStatus]
            , AF.[BlockConsumptionCost]     AS [AF_BlockConsumptionCost]
            , AF.[TotalConsumptionCost]     AS [AF_TotalConsumptionCost]
            , AF.[APUConsumptionVol]        AS [AF_APUConsumptionVol]
            , AF.[APUConsumptionMass]       AS [AF_APUConsumptionMass]
            , AF.[APUConsumptionCost]       AS [AF_APUConsumptionCost]
            , AF.[TankeredFuelVol]          AS [AF_TankeredFuelVol]
            , AF.[TankeredFuelMass]         AS [AF_TankeredFuelMass]
            , AF.[Division]                 AS [AF_Division]
            , AF.[FlightSeqNo]              AS [AF_FlightSeqNo]
            , AF.[FlightType]               AS [AF_FlightType]
            , AF.[ServiceType]              AS [AF_ServiceType]
            , AF.[ReportedCustomer]         AS [AF_ReportedCustomer]
            , AF.[LegDistance]              AS [AF_LegDistance]

            , CAL.[Date]                    AS [CAL_Date]
            , CAL.[CRT_DT]                  AS [CAL_CRT_DT]
            , CAL.[DOW]                     AS [CAL_DOW]
            , CAL.[YR]                      AS [CAL_YR]
            , CAL.[QT]                      AS [CAL_QT]
            , CAL.[MTH]                     AS [CAL_MTH]
            , CAL.[Y2D]                     AS [CAL_Y2D]
            , CAL.[Q2D]                     AS [CAL_Q2D]
            , CAL.[M2D]                     AS [CAL_M2D]
            , CAL.[W2D]                     AS [CAL_W2D]
            , CAL.[ANY_Y2D]                 AS [CAL_ANY_Y2D]
            , CAL.[ANY_Q2D]                 AS [CAL_ANY_Q2D]
            , CAL.[SAME_Q2D]                AS [CAL_SAME_Q2D]
            , CAL.[ANY_M2D]                 AS [CAL_ANY_M2D]
            , CAL.[SAME_M2D]                AS [CAL_SAME_M2D]

            , GEO.[LOC_ID]                  AS [GEO_LOC_ID]
            , GEO.[LocationCode]            AS [GEO_LocationCode]
            , GEO.[LocationName]            AS [GEO_LocationName]
            , GEO.[LocationIATACode]        AS [GEO_LocationIATACode]
            , GEO.[LocationICAOCode]        AS [GEO_LocationICAOCode]
            , GEO.[IsAirport]               AS [GEO_IsAirport]
            , GEO.[CNTRY_ID]                AS [GEO_CNTRY_ID]
            , GEO.[CountryName]             AS [GEO_CountryName]
            , GEO.[CountryISOCode]          AS [GEO_CountryISOCode]
            , GEO.[Continent]               AS [GEO_Continent]

            , GEO2.[LOC_ID]                 AS [GEO2_LOC_ID]
            , GEO2.[LocationCode]           AS [GEO2_LocationCode]
            , GEO2.[LocationName]           AS [GEO2_LocationName]
            , GEO2.[LocationIATACode]       AS [GEO2_LocationIATACode]
            , GEO2.[LocationICAOCode]       AS [GEO2_LocationICAOCode]
            , GEO2.[IsAirport]              AS [GEO2_IsAirport]
            , GEO2.[CNTRY_ID]               AS [GEO2_CNTRY_ID]
            , GEO2.[CountryName]            AS [GEO2_CountryName]
            , GEO2.[CountryISOCode]         AS [GEO2_CountryISOCode]
            , GEO2.[Continent]              AS [GEO2_Continent]

            , AIR.[CO_ID]                   AS [AIR_CO_ID]
            , AIR.[AirlineCode]             AS [AIR_AirlineCode]
            , AIR.[AirlineName]             AS [AIR_AirlineName]
            , AIR.[AirlineIATACode]         AS [AIR_AirlineIATACode]
            , AIR.[AirlineICAOCode]         AS [AIR_AirlineICAOCode]
            , AIR.[CO_GRP_ID]               AS [AIR_CO_GRP_ID]
            , AIR.[GroupCode]               AS [AIR_GroupCode]
            , AIR.[GroupName]               AS [AIR_GroupName]

            , AIR2.[CO_ID]                  AS [AIR2_CO_ID]
            , AIR2.[AirlineCode]            AS [AIR2_AirlineCode]
            , AIR2.[AirlineName]            AS [AIR2_AirlineName]
            , AIR2.[AirlineIATACode]        AS [AIR2_AirlineIATACode]
            , AIR2.[AirlineICAOCode]        AS [AIR2_AirlineICAOCode]
            , AIR2.[CO_GRP_ID]              AS [AIR2_CO_GRP_ID]
            , AIR2.[GroupCode]              AS [AIR2_GroupCode]
            , AIR2.[GroupName]              AS [AIR2_GroupName]

            , CA.[LoginName]                AS [CA_LoginName]
            , CA.[CO_ID]                    AS [CA_CO_ID]
            , CA.[CustomerCode]             AS [CA_CustomerCode]
            , CA.[CustomerName]             AS [CA_CustomerName]
            , CA.[CustomerICAOCode]         AS [CA_CustomerICAOCode]

            , CUS.[CO_ID]                   AS [CUS_CO_ID]
            , CUS.[CustomerCode]            AS [CUS_CustomerCode]
            , CUS.[CustomerICAOCode]        AS [CUS_CustomerICAOCode]
            , CUS.[CustomerName]            AS [CUS_CustomerName]
            , CUS.[CO_GRP_ID]               AS [CUS_CO_GRP_ID]
            , CUS.[GroupCode]               AS [CUS_GroupCode]
            , CUS.[GroupName]               AS [CUS_GroupName]
            , CUS.[CLIENT_ID]               AS [CUS_CLIENT_ID]
            , CUS.[ClientCode]              AS [CUS_ClientCode]
            , CUS.[ClientName]              AS [CUS_ClientName]
        INTO [fpx].[Report_Uplift_Consumption_Tankering]
        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_ActualFlights] AF
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Calendar]       CAL  ON CAL.[Date] = AF.[DepartureDate]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography]      GEO  ON AF.[Departure]    = GEO.[LocationIATACode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography]      GEO2 ON AF.[Destination]  = GEO2.[LocationIATACode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Airline]        AIR  ON AF.[Owner]        = AIR.[AirlineICAOCode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Airline]        AIR2 ON AF.[Operator]     = AIR2.[AirlineICAOCode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_CustomerAccess] CA   ON AF.[Customer]     = CA.[CustomerICAOCode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Customer]       CUS  ON CA.[CustomerICAOCode] = CUS.[CustomerICAOCode];
    END
    ELSE
    BEGIN
        TRUNCATE TABLE [fpx].[Report_Uplift_Consumption_Tankering];

        INSERT INTO [fpx].[Report_Uplift_Consumption_Tankering] 
              
        SELECT
              AF.[FlightID]                 AS [AF_FlightID]
            , AF.[FlightDate]               AS [AF_FlightDate]
            , CONCAT(YEAR(AF.[FlightDate]),' ',RIGHT('00' + CAST(DATEPART(WEEK, AF.[FlightDate]) AS VARCHAR(2)), 2)) AS WeeksLabel
            , CAST(YEAR(AF.[FlightDate]) AS INT) * 100 + DATEPART(WEEK, AF.[FlightDate]) AS WeekKey
            , AF.[Registration]             AS [AF_Registration]
            , AF.[Departure]                AS [AF_Departure]
            , AF.[Destination]              AS [AF_Destination]
            , AF.[AirlineDesignator]        AS [AF_AirlineDesignator]
            , AF.[FlightNumber]             AS [AF_FlightNumber]
            , AF.[Suffix]                   AS [AF_Suffix]
            , AF.[AircraftType]             AS [AF_AircraftType]
            , AF.[Leg]                      AS [AF_Leg]
            , AF.[LegAircraftType]          AS [AF_LegAircraftType]
            , AF.[SpecialEvent]             AS [AF_SpecialEvent]
            , AF.[DomInt]                   AS [AF_DomInt]
            , AF.[DepartureDate]            AS [AF_DepartureDate]
            , AF.[OffBlockTimeUTC]          AS [AF_OffBlockTimeUTC]
            , AF.[TakeOffTimeUTC]           AS [AF_TakeOffTimeUTC]
            , AF.[TouchDownTimeUTC]         AS [AF_TouchDownTimeUTC]
            , AF.[OnBlockTimeUTC]           AS [AF_OnBlockTimeUTC]
            , AF.[BlockTime]                AS [AF_BlockTime]
            , AF.[FlightTime]               AS [AF_FlightTime]
            , AF.[Operator]                 AS [AF_Operator]
            , AF.[Owner]                    AS [AF_Owner]
            , AF.[Customer]                 AS [AF_Customer]
            , AF.[UpliftVol]                AS [AF_UpliftVol]
            , AF.[UpliftMass]               AS [AF_UpliftMass]
            , AF.[UpliftDensity]            AS [AF_UpliftDensity]
            , AF.[UpliftStatus]             AS [AF_UpliftStatus]
            , AF.[UpliftCost]               AS [AF_UpliftCost]
            , AF.[IPStatus]                 AS [AF_IPStatus]
            , AF.[BeforeFuelingVol]         AS [AF_BeforeFuelingVol]
            , AF.[BeforeFuelingMass]        AS [AF_BeforeFuelingMass]
            , AF.[OffBlockFuelVol]          AS [AF_OffBlockFuelVol]
            , AF.[OffBlockFuelMass]         AS [AF_OffBlockFuelMass]
            , AF.[ShutDownFuelVol]          AS [AF_ShutDownFuelVol]
            , AF.[ShutDownFuelMass]         AS [AF_ShutDownFuelMass]
            , AF.[FuelDumpVol]              AS [AF_FuelDumpVol]
            , AF.[FuelDumpMass]             AS [AF_FuelDumpMass]
            , AF.[BlockConsumptionVol]      AS [AF_BlockConsumptionVol]
            , AF.[BlockConsumptionMass]     AS [AF_BlockConsumptionMass]
            , AF.[BlockConsumptionStatus]   AS [AF_BlockConsumptionStatus]
            , AF.[TotalConsumptionVol]      AS [AF_TotalConsumptionVol]
            , AF.[TotalConsumptionMass]     AS [AF_TotalConsumptionMass]
            , AF.[TotalConsumptionStatus]   AS [AF_TotalConsumptionStatus]
            , AF.[BlockConsumptionCost]     AS [AF_BlockConsumptionCost]
            , AF.[TotalConsumptionCost]     AS [AF_TotalConsumptionCost]
            , AF.[APUConsumptionVol]        AS [AF_APUConsumptionVol]
            , AF.[APUConsumptionMass]       AS [AF_APUConsumptionMass]
            , AF.[APUConsumptionCost]       AS [AF_APUConsumptionCost]
            , AF.[TankeredFuelVol]          AS [AF_TankeredFuelVol]
            , AF.[TankeredFuelMass]         AS [AF_TankeredFuelMass]
            , AF.[Division]                 AS [AF_Division]
            , AF.[FlightSeqNo]              AS [AF_FlightSeqNo]
            , AF.[FlightType]               AS [AF_FlightType]
            , AF.[ServiceType]              AS [AF_ServiceType]
            , AF.[ReportedCustomer]         AS [AF_ReportedCustomer]
            , AF.[LegDistance]              AS [AF_LegDistance]
            , CAL.[Date]                    AS [CAL_Date]
            , CAL.[CRT_DT]                  AS [CAL_CRT_DT]
            , CAL.[DOW]                     AS [CAL_DOW]
            , CAL.[YR]                      AS [CAL_YR]
            , CAL.[QT]                      AS [CAL_QT]
            , CAL.[MTH]                     AS [CAL_MTH]
            , CAL.[Y2D]                     AS [CAL_Y2D]
            , CAL.[Q2D]                     AS [CAL_Q2D]
            , CAL.[M2D]                     AS [CAL_M2D]
            , CAL.[W2D]                     AS [CAL_W2D]
            , CAL.[ANY_Y2D]                 AS [CAL_ANY_Y2D]
            , CAL.[ANY_Q2D]                 AS [CAL_ANY_Q2D]
            , CAL.[SAME_Q2D]                AS [CAL_SAME_Q2D]
            , CAL.[ANY_M2D]                 AS [CAL_ANY_M2D]
            , CAL.[SAME_M2D]                AS [CAL_SAME_M2D]
            , GEO.[LOC_ID]                  AS [GEO_LOC_ID]
            , GEO.[LocationCode]            AS [GEO_LocationCode]
            , GEO.[LocationName]            AS [GEO_LocationName]
            , GEO.[LocationIATACode]        AS [GEO_LocationIATACode]
            , GEO.[LocationICAOCode]        AS [GEO_LocationICAOCode]
            , GEO.[IsAirport]               AS [GEO_IsAirport]
            , GEO.[CNTRY_ID]                AS [GEO_CNTRY_ID]
            , GEO.[CountryName]             AS [GEO_CountryName]
            , GEO.[CountryISOCode]          AS [GEO_CountryISOCode]
            , GEO.[Continent]               AS [GEO_Continent]
            , GEO2.[LOC_ID]                 AS [GEO2_LOC_ID]
            , GEO2.[LocationCode]           AS [GEO2_LocationCode]
            , GEO2.[LocationName]           AS [GEO2_LocationName]
            , GEO2.[LocationIATACode]       AS [GEO2_LocationIATACode]
            , GEO2.[LocationICAOCode]       AS [GEO2_LocationICAOCode]
            , GEO2.[IsAirport]              AS [GEO2_IsAirport]
            , GEO2.[CNTRY_ID]               AS [GEO2_CNTRY_ID]
            , GEO2.[CountryName]            AS [GEO2_CountryName]
            , GEO2.[CountryISOCode]         AS [GEO2_CountryISOCode]
            , GEO2.[Continent]              AS [GEO2_Continent]
            , AIR.[CO_ID]                   AS [AIR_CO_ID]
            , AIR.[AirlineCode]             AS [AIR_AirlineCode]
            , AIR.[AirlineName]             AS [AIR_AirlineName]
            , AIR.[AirlineIATACode]         AS [AIR_AirlineIATACode]
            , AIR.[AirlineICAOCode]         AS [AIR_AirlineICAOCode]
            , AIR.[CO_GRP_ID]               AS [AIR_CO_GRP_ID]
            , AIR.[GroupCode]               AS [AIR_GroupCode]
            , AIR.[GroupName]               AS [AIR_GroupName]
            , AIR2.[CO_ID]                  AS [AIR2_CO_ID]
            , AIR2.[AirlineCode]            AS [AIR2_AirlineCode]
            , AIR2.[AirlineName]            AS [AIR2_AirlineName]
            , AIR2.[AirlineIATACode]        AS [AIR2_AirlineIATACode]
            , AIR2.[AirlineICAOCode]        AS [AIR2_AirlineICAOCode]
            , AIR2.[CO_GRP_ID]              AS [AIR2_CO_GRP_ID]
            , AIR2.[GroupCode]              AS [AIR2_GroupCode]
            , AIR2.[GroupName]              AS [AIR2_GroupName]
            , CA.[LoginName]                AS [CA_LoginName]
            , CA.[CO_ID]                    AS [CA_CO_ID]
            , CA.[CustomerCode]             AS [CA_CustomerCode]
            , CA.[CustomerName]             AS [CA_CustomerName]
            , CA.[CustomerICAOCode]         AS [CA_CustomerICAOCode]
            , CUS.[CO_ID]                   AS [CUS_CO_ID]
            , CUS.[CustomerCode]            AS [CUS_CustomerCode]
            , CUS.[CustomerICAOCode]        AS [CUS_CustomerICAOCode]
            , CUS.[CustomerName]            AS [CUS_CustomerName]
            , CUS.[CO_GRP_ID]               AS [CUS_CO_GRP_ID]
            , CUS.[GroupCode]               AS [CUS_GroupCode]
            , CUS.[GroupName]               AS [CUS_GroupName]
            , CUS.[CLIENT_ID]               AS [CUS_CLIENT_ID]
            , CUS.[ClientCode]              AS [CUS_ClientCode]
            , CUS.[ClientName]              AS [CUS_ClientName]
        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_ActualFlights] AF
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Calendar]       CAL  ON CAL.[Date] = AF.[DepartureDate]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography]      GEO  ON AF.[Departure]    = GEO.[LocationIATACode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography]      GEO2 ON AF.[Destination]  = GEO2.[LocationIATACode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Airline]        AIR  ON AF.[Owner]        = AIR.[AirlineICAOCode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Airline]        AIR2 ON AF.[Operator]     = AIR2.[AirlineICAOCode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_CustomerAccess] CA   ON AF.[Customer]     = CA.[CustomerICAOCode]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Customer]       CUS  ON CA.[CustomerICAOCode] = CUS.[CustomerICAOCode];
    END
END