CREATE  PROCEDURE [fpx].[usp_emissions]
AS
BEGIN
    SET NOCOUNT ON;

    -- Check if destination table exists
    IF OBJECT_ID('[fpx].[Report_Emissions]', 'U') IS NULL
    BEGIN
        CREATE TABLE [fpx].[Report_Emissions] AS
        SELECT 
            -- AF columns
            AF.FlightID AS AF_FlightID,
            AF.FlightDate AS AF_FlightDate,
            AF.Registration AS AF_Registration,
            AF.Departure,
            AF.Destination,
            AF.Departure + '-' + AF.Destination AS Route,
            AF.AirlineDesignator AS AF_AirlineDesignator,
            AF.FlightNumber AS AF_FlightNumber,
            AF.Suffix AS AF_Suffix,
            AF.AircraftID,
            AF.AircraftType,
            AF.OpsAircraftType,
            AF.Leg,
            AF.LegAircraftType,
            AF.SpecialEvent AS AF_SpecialEvent,
            AF.DomInt,
            AF.DepartureDate AS AF_DepartureDate,
            AF.OffBlockTimeUTC AS AF_OffBlockTimeUTC,
            AF.TakeOffTimeUTC AS AF_TakeOffTimeUTC,
            AF.TouchDownTimeUTC AS AF_TouchDownTimeUTC,
            AF.OnBlockTimeUTC AS AF_OnBlockTimeUTC,
            AF.BlockTime AS AF_BlockTime,
            AF.FlightTime AS AF_FlightTime,
            AF.Operator,
            AF.Owner AS AF_Owner,
            AF.Customer AS AF_Customer,
            AF.UpliftVol,
            AF.UpliftMass,
            AF.UpliftDensity,
            AF.UpliftStatus,
            AF.UpliftCost,
            AF.IPStatus,
            AF.BeforeFuelingVol,
            AF.BeforeFuelingMass,
            AF.OffBlockFuelVol,
            AF.OffBlockFuelMass,
            AF.ShutDownFuelVol,
            AF.ShutDownFuelMass,
            AF.FuelDumpVol,
            AF.FuelDumpMass,
            AF.BlockConsumptionVol,
            AF.BlockConsumptionMass,
            AF.BlockConsumptionStatus,
            AF.TotalConsumptionVol,
            AF.TotalConsumptionMass,
            AF.TotalConsumptionStatus,
            AF.BlockConsumptionCost,
            AF.TotalConsumptionCost,
            AF.APUConsumptionVol,
            AF.APUConsumptionMass,
            AF.APUConsumptionCost,
            AF.TankeredFuelVol,
            AF.TankeredFuelMass,
            AF.Division AS AF_Division,
            AF.FlightSeqNo,
            AF.FlightType AS AF_FlightType,
            AF.ServiceType AS AF_ServiceType,
            AF.ReportedCustomer,
            AF.FinalCustomer,
            AF.LegDistance AS AF_LegDistance,
            AF.CharterContractNo,
            AF.Terminal,
            AF.GateNo,
            AF.StandNo,
            AF.AirportArea,

            -- ETS columns
            ETS.ETSDataID,
            ETS.ETS,
            ETS.FlightId AS ETS_FlightID,
            ETS.DepartureDateLT,
            ETS.DepartureDateUTC,
            ETS.FlightDate AS ETS_FlightDate,
            ETS.AirlineDesignator AS ETS_AirlineDesignator,
            ETS.FlightNumber AS ETS_FlightNumber,
            ETS.Suffix AS ETS_Suffix,
            ETS.Registration AS ETS_Registration,
            ETS.Departure AS ETS_Departure,
            ETS.Destination AS ETS_Destination,
            ETS.ScheduledDestination,
            ETS.AcType,
            ETS.Customer AS ETS_Customer,
            ETS.Owner AS ETS_Owner,
            ETS.IcaoDeparture,
            ETS.IcaoDestination,
            ETS.DepartureCountry,
            ETS.DestinationCountry,
            ETS.OffBlockTimeUTC AS ETS_OffBlockTimeUTC,
            ETS.TakeOffTimeUTC AS ETS_TakeOffTimeUTC,
            ETS.TouchDownTimeUTC AS ETS_TouchDownTimeUTC,
            ETS.OnBlockTimeUTC AS ETS_OnBlockTimeUTC,
            ETS.OffBlockTimeLT,
            ETS.BlockTime AS ETS_BlockTime,
            ETS.FlightTime AS ETS_FlightTime,
            ETS.BlockTimeDec,
            ETS.FlightTimeDec,
            ETS.SpecialEvent AS ETS_SpecialEvent,
            ETS.Diverted,
            ETS.IcaoDesignator,
            ETS.IcaoCallSign,
            ETS.MissionId,
            ETS.Division AS ETS_Division,
            ETS.FlightType AS ETS_FlightType,
            ETS.ServiceType AS ETS_ServiceType,
            ETS.OpsUplift,
            ETS.OpsUpliftStatus,
            ETS.OpsUpliftMsgSrc,
            ETS.OpsUpliftMsgStatus,
            ETS.OpsDensity,
            ETS.OpsDensitySrc,
            ETS.OpsDensityMsgSrc,
            ETS.OpsTotalConsumption,
            ETS.OpsTotalConsumptionStatus,
            ETS.OpsBlockConsumption,
            ETS.OpsBlockConsumptionStatus,
            ETS.ETSFuelBeforeUp,
            ETS.ETSFuelBeforeUpStatus,
            ETS.ETSFuelBeforeUpMsgSrc,
            ETS.ETSUplift,
            ETS.ETSUpliftStatus,
            ETS.ETSUpliftMsgSrc,
            ETS.ETSDensity,
            ETS.ETSDensitySrc,
            ETS.ETSDensityMsgSrc,
            ETS.ETSFuelAfterUp,
            ETS.ETSFuelAfterUpStatus,
            ETS.ETSFuelAfterUpMsgSrc,
            ETS.ETSFuelShutdown,
            ETS.ETSFuelShutdownStatus,
            ETS.ETSFuelShutdownMsgSrc,
            ETS.ETSRelevant,
            ETS.ETSMethod,
            ETS.FuelType,
            ETS.MaxConsumptionReason,
            ETS.SpecialConsumptionReason,
            ETS.ConsumptionManuallySet,
            ETS.ETSConsumption,
            ETS.ETSConsumptionStatus,
            ETS.ETSConsumptionFormula,
            ETS.ETSConsumptionFormulaVal,
            ETS.CO2Emission,
            ETS.PayloadNet,
            ETS.PaxMass,
            ETS.CargoMass,
            ETS.PaxTotal,
            ETS.LoadsheetStatus,
            ETS.LegDistance AS ETS_LegDistance,
            ETS.ETSDistance,

            -- GEO columns
            GEO.LOC_ID,
            GEO.LocationCode,
            GEO.LocationName,
            GEO.LocationIATACode,
            GEO.LocationICAOCode,
            GEO.IsAirport,
            GEO.IsMonopolistic,
            GEO.CNTRY_ID,
            GEO.CountryName,
            GEO.CountryISOCode,
            GEO.Continent,
            GEO.StateCode,
            GEO.StateName

        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_ActualFlights] AF
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLF_ETSData] ETS ON AF.FlightID = ETS.FlightId
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography] GEO ON AF.Departure = GEO.LocationCode;
    END
    ELSE
    BEGIN
        TRUNCATE TABLE [fpx].[Report_Emissions];

        INSERT INTO [fpx].[Report_Emissions]
        SELECT 
 -- AF columns
            AF.FlightID AS AF_FlightID,
            AF.FlightDate AS AF_FlightDate,
            AF.Registration AS AF_Registration,
            AF.Departure,
            AF.Destination,
            AF.Departure + '-' + AF.Destination AS Route,
            AF.AirlineDesignator AS AF_AirlineDesignator,
            AF.FlightNumber AS AF_FlightNumber,
            AF.Suffix AS AF_Suffix,
            AF.AircraftID,
            AF.AircraftType,
            AF.OpsAircraftType,
            AF.Leg,
            AF.LegAircraftType,
            AF.SpecialEvent AS AF_SpecialEvent,
            AF.DomInt,
            AF.DepartureDate AS AF_DepartureDate,
            AF.OffBlockTimeUTC AS AF_OffBlockTimeUTC,
            AF.TakeOffTimeUTC AS AF_TakeOffTimeUTC,
            AF.TouchDownTimeUTC AS AF_TouchDownTimeUTC,
            AF.OnBlockTimeUTC AS AF_OnBlockTimeUTC,
            AF.BlockTime AS AF_BlockTime,
            AF.FlightTime AS AF_FlightTime,
            AF.Operator,
            AF.Owner AS AF_Owner,
            AF.Customer AS AF_Customer,
            AF.UpliftVol,
            AF.UpliftMass,
            AF.UpliftDensity,
            AF.UpliftStatus,
            AF.UpliftCost,
            AF.IPStatus,
            AF.BeforeFuelingVol,
            AF.BeforeFuelingMass,
            AF.OffBlockFuelVol,
            AF.OffBlockFuelMass,
            AF.ShutDownFuelVol,
            AF.ShutDownFuelMass,
            AF.FuelDumpVol,
            AF.FuelDumpMass,
            AF.BlockConsumptionVol,
            AF.BlockConsumptionMass,
            AF.BlockConsumptionStatus,
            AF.TotalConsumptionVol,
            AF.TotalConsumptionMass,
            AF.TotalConsumptionStatus,
            AF.BlockConsumptionCost,
            AF.TotalConsumptionCost,
            AF.APUConsumptionVol,
            AF.APUConsumptionMass,
            AF.APUConsumptionCost,
            AF.TankeredFuelVol,
            AF.TankeredFuelMass,
            AF.Division AS AF_Division,
            AF.FlightSeqNo,
            AF.FlightType AS AF_FlightType,
            AF.ServiceType AS AF_ServiceType,
            AF.ReportedCustomer,
            AF.FinalCustomer,
            AF.LegDistance AS AF_LegDistance,
            AF.CharterContractNo,
            AF.Terminal,
            AF.GateNo,
            AF.StandNo,
            AF.AirportArea,

            -- ETS columns
            ETS.ETSDataID,
            ETS.ETS,
            ETS.FlightId AS ETS_FlightID,
            ETS.DepartureDateLT,
            ETS.DepartureDateUTC,
            ETS.FlightDate AS ETS_FlightDate,
            ETS.AirlineDesignator AS ETS_AirlineDesignator,
            ETS.FlightNumber AS ETS_FlightNumber,
            ETS.Suffix AS ETS_Suffix,
            ETS.Registration AS ETS_Registration,
            ETS.Departure AS ETS_Departure,
            ETS.Destination AS ETS_Destination,
            ETS.ScheduledDestination,
            ETS.AcType,
            ETS.Customer AS ETS_Customer,
            ETS.Owner AS ETS_Owner,
            ETS.IcaoDeparture,
            ETS.IcaoDestination,
            ETS.DepartureCountry,
            ETS.DestinationCountry,
            ETS.OffBlockTimeUTC AS ETS_OffBlockTimeUTC,
            ETS.TakeOffTimeUTC AS ETS_TakeOffTimeUTC,
            ETS.TouchDownTimeUTC AS ETS_TouchDownTimeUTC,
            ETS.OnBlockTimeUTC AS ETS_OnBlockTimeUTC,
            ETS.OffBlockTimeLT,
            ETS.BlockTime AS ETS_BlockTime,
            ETS.FlightTime AS ETS_FlightTime,
            ETS.BlockTimeDec,
            ETS.FlightTimeDec,
            ETS.SpecialEvent AS ETS_SpecialEvent,
            ETS.Diverted,
            ETS.IcaoDesignator,
            ETS.IcaoCallSign,
            ETS.MissionId,
            ETS.Division AS ETS_Division,
            ETS.FlightType AS ETS_FlightType,
            ETS.ServiceType AS ETS_ServiceType,
            ETS.OpsUplift,
            ETS.OpsUpliftStatus,
            ETS.OpsUpliftMsgSrc,
            ETS.OpsUpliftMsgStatus,
            ETS.OpsDensity,
            ETS.OpsDensitySrc,
            ETS.OpsDensityMsgSrc,
            ETS.OpsTotalConsumption,
            ETS.OpsTotalConsumptionStatus,
            ETS.OpsBlockConsumption,
            ETS.OpsBlockConsumptionStatus,
            ETS.ETSFuelBeforeUp,
            ETS.ETSFuelBeforeUpStatus,
            ETS.ETSFuelBeforeUpMsgSrc,
            ETS.ETSUplift,
            ETS.ETSUpliftStatus,
            ETS.ETSUpliftMsgSrc,
            ETS.ETSDensity,
            ETS.ETSDensitySrc,
            ETS.ETSDensityMsgSrc,
            ETS.ETSFuelAfterUp,
            ETS.ETSFuelAfterUpStatus,
            ETS.ETSFuelAfterUpMsgSrc,
            ETS.ETSFuelShutdown,
            ETS.ETSFuelShutdownStatus,
            ETS.ETSFuelShutdownMsgSrc,
            ETS.ETSRelevant,
            ETS.ETSMethod,
            ETS.FuelType,
            ETS.MaxConsumptionReason,
            ETS.SpecialConsumptionReason,
            ETS.ConsumptionManuallySet,
            ETS.ETSConsumption,
            ETS.ETSConsumptionStatus,
            ETS.ETSConsumptionFormula,
            ETS.ETSConsumptionFormulaVal,
            ETS.CO2Emission,
            ETS.PayloadNet,
            ETS.PaxMass,
            ETS.CargoMass,
            ETS.PaxTotal,
            ETS.LoadsheetStatus,
            ETS.LegDistance AS ETS_LegDistance,
            ETS.ETSDistance,

            -- GEO columns
            GEO.LOC_ID,
            GEO.LocationCode,
            GEO.LocationName,
            GEO.LocationIATACode,
            GEO.LocationICAOCode,
            GEO.IsAirport,
            GEO.IsMonopolistic,
            GEO.CNTRY_ID,
            GEO.CountryName,
            GEO.CountryISOCode,
            GEO.Continent,
            GEO.StateCode,
            GEO.StateName

        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_ActualFlights] AF
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLF_ETSData] ETS ON AF.FlightID = ETS.FlightId
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography] GEO ON AF.Departure = GEO.LocationCode;
    END
END