CREATE  PROCEDURE [fpx].[usp_supplier_volumes]
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID('[fpx].[Report_Supplier_Volumes]', 'U') IS NULL
    BEGIN
        SELECT
              SV.[ContractID]              AS [SV_ContractID]
            , SV.[ContractCode]            AS [SV_ContractCode]
            , SV.[LOC_ID]                  AS [SV_LOC_ID]
            , SV.[LOC_CD]                  AS [SV_LOC_CD]
            , SV.[ContractType]            AS [SV_ContractType]
            , SV.[HLDR_CO_ID]              AS [SV_HLDR_CO_ID]
            , SV.[HLDR_CO_CD]              AS [SV_HLDR_CO_CD]
            , SV.[CNTPRTY_CO_ID]           AS [SV_CNTPRTY_CO_ID]
            , SV.[CP_CO_CD]                AS [SV_CP_CO_CD]
            , SV.[ContractValidFrom]       AS [SV_ContractValidFrom]
            , SV.[ContractValidTo]         AS [SV_ContractValidTo]
            , SV.[CO_GRP_ID]               AS [SV_CO_GRP_ID]
            , SV.[CO_GRP_CD]               AS [SV_CO_GRP_CD]
            , SV.[CUST_CO_ID]              AS [SV_CUST_CO_ID]
            , SV.[CUST_CO_CD]              AS [SV_CUST_CO_CD]
            , SV.[Month]                   AS [SV_Month]
            , SV.[InitialVolume]           AS [SV_InitialVolume]
            , SV.[AdjustedVolume]          AS [SV_AdjustedVolume]
            , SV.[OrderedVolume]           AS [SV_OrderedVolume]
            , SV.[ActualVolume]            AS [SV_ActualVolume]
            , SV.[PeriodIndicator]         AS [SV_PeriodIndicator]

            , CAL.[Date]                   AS [CAL_Date]
            , CAL.[CRT_DT]                 AS [CAL_CRT_DT]
            , CAL.[DOW]                    AS [CAL_DOW]
            , CAL.[YR]                     AS [CAL_YR]
            , CAL.[QT]                     AS [CAL_QT]
            , CAL.[MTH]                    AS [CAL_MTH]
            , CAL.[Y2D]                    AS [CAL_Y2D]
            , CAL.[Q2D]                    AS [CAL_Q2D]
            , CAL.[M2D]                    AS [CAL_M2D]
            , CAL.[W2D]                    AS [CAL_W2D]
            , CAL.[ANY_Y2D]                AS [CAL_ANY_Y2D]
            , CAL.[ANY_Q2D]                AS [CAL_ANY_Q2D]
            , CAL.[SAME_Q2D]               AS [CAL_SAME_Q2D]
            , CAL.[ANY_M2D]                AS [CAL_ANY_M2D]
            , CAL.[SAME_M2D]               AS [CAL_SAME_M2D]

            , GEO.[LOC_ID]                 AS [GEO_LOC_ID]
            , GEO.[LocationCode]           AS [GEO_LocationCode]
            , GEO.[LocationName]           AS [GEO_LocationName]
            , GEO.[LocationIATACode]       AS [GEO_LocationIATACode]
            , GEO.[LocationICAOCode]       AS [GEO_LocationICAOCode]
            , GEO.[IsAirport]              AS [GEO_IsAirport]
            , GEO.[CNTRY_ID]               AS [GEO_CNTRY_ID]
            , GEO.[CountryName]            AS [GEO_CountryName]
            , GEO.[CountryISOCode]         AS [GEO_CountryISOCode]
            , GEO.[Continent]              AS [GEO_Continent]

            , CUS.[CO_ID]                  AS [CUS_CO_ID]
            , CUS.[CustomerCode]           AS [CUS_CustomerCode]
            , CUS.[CustomerICAOCode]       AS [CUS_CustomerICAOCode]
            , CUS.[CustomerName]           AS [CUS_CustomerName]
            , CUS.[CO_GRP_ID]              AS [CUS_CO_GRP_ID]
            , CUS.[GroupCode]              AS [CUS_GroupCode]
            , CUS.[GroupName]              AS [CUS_GroupName]
            , CUS.[CLIENT_ID]              AS [CUS_CLIENT_ID]
            , CUS.[ClientCode]             AS [CUS_ClientCode]
            , CUS.[ClientName]             AS [CUS_ClientName]

            , CH.[CO_ID]                   AS [CH_CO_ID]
            , CH.[ContractHolderCode]      AS [CH_ContractHolderCode]
            , CH.[ContractHolderName]      AS [CH_ContractHolderName]
            , CH.[CO_GRP_ID]               AS [CH_CO_GRP_ID]
            , CH.[GroupCode]               AS [CH_GroupCode]
            , CH.[GroupName]               AS [CH_GroupName]
            , CH.[CLIENT_ID]               AS [CH_CLIENT_ID]
            , CH.[ClientCode]              AS [CH_ClientCode]
            , CH.[ClientName]              AS [CH_ClientName]

            , SUP.[CO_ID]                  AS [SUP_CO_ID]
            , SUP.[SupplierCode]           AS [SUP_SupplierCode]
            , SUP.[SupplierName]           AS [SUP_SupplierName]
            , SUP.[SupplierCode2]          AS [SUP_SupplierCode2]
            , SUP.[SupplierCode3]          AS [SUP_SupplierCode3]

        INTO [fpx].[Report_Supplier_Volumes]
        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_SupplierVolumes]       SV
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Calendar]   CAL ON CAL.[Date]     = SV.[Month]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography]  GEO ON GEO.[LOC_ID]   = SV.[LOC_ID]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Customer]   CUS ON CUS.[CO_ID]    = SV.[CUST_CO_ID]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_ContractHolder] CH  ON CH.[CO_ID] = SV.[HLDR_CO_ID]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Supplier]   SUP ON SUP.[CO_ID]    = SV.[CNTPRTY_CO_ID];
    END
    ELSE
    BEGIN
        TRUNCATE TABLE [fpx].[Report_Supplier_Volumes];

        INSERT INTO [fpx].[Report_Supplier_Volumes]
        SELECT
              SV.[ContractID]              AS [SV_ContractID]
            , SV.[ContractCode]            AS [SV_ContractCode]
            , SV.[LOC_ID]                  AS [SV_LOC_ID]
            , SV.[LOC_CD]                  AS [SV_LOC_CD]
            , SV.[ContractType]            AS [SV_ContractType]
            , SV.[HLDR_CO_ID]              AS [SV_HLDR_CO_ID]
            , SV.[HLDR_CO_CD]              AS [SV_HLDR_CO_CD]
            , SV.[CNTPRTY_CO_ID]           AS [SV_CNTPRTY_CO_ID]
            , SV.[CP_CO_CD]                AS [SV_CP_CO_CD]
            , SV.[ContractValidFrom]       AS [SV_ContractValidFrom]
            , SV.[ContractValidTo]         AS [SV_ContractValidTo]
            , SV.[CO_GRP_ID]               AS [SV_CO_GRP_ID]
            , SV.[CO_GRP_CD]               AS [SV_CO_GRP_CD]
            , SV.[CUST_CO_ID]              AS [SV_CUST_CO_ID]
            , SV.[CUST_CO_CD]              AS [SV_CUST_CO_CD]
            , SV.[Month]                   AS [SV_Month]
            , SV.[InitialVolume]           AS [SV_InitialVolume]
            , SV.[AdjustedVolume]          AS [SV_AdjustedVolume]
            , SV.[OrderedVolume]           AS [SV_OrderedVolume]
            , SV.[ActualVolume]            AS [SV_ActualVolume]
            , SV.[PeriodIndicator]         AS [SV_PeriodIndicator]

            , CAL.[Date]                   AS [CAL_Date]
            , CAL.[CRT_DT]                 AS [CAL_CRT_DT]
            , CAL.[DOW]                    AS [CAL_DOW]
            , CAL.[YR]                     AS [CAL_YR]
            , CAL.[QT]                     AS [CAL_QT]
            , CAL.[MTH]                    AS [CAL_MTH]
            , CAL.[Y2D]                    AS [CAL_Y2D]
            , CAL.[Q2D]                    AS [CAL_Q2D]
            , CAL.[M2D]                    AS [CAL_M2D]
            , CAL.[W2D]                    AS [CAL_W2D]
            , CAL.[ANY_Y2D]                AS [CAL_ANY_Y2D]
            , CAL.[ANY_Q2D]                AS [CAL_ANY_Q2D]
            , CAL.[SAME_Q2D]               AS [CAL_SAME_Q2D]
            , CAL.[ANY_M2D]                AS [CAL_ANY_M2D]
            , CAL.[SAME_M2D]               AS [CAL_SAME_M2D]

            , GEO.[LOC_ID]                 AS [GEO_LOC_ID]
            , GEO.[LocationCode]           AS [GEO_LocationCode]
            , GEO.[LocationName]           AS [GEO_LocationName]
            , GEO.[LocationIATACode]       AS [GEO_LocationIATACode]
            , GEO.[LocationICAOCode]       AS [GEO_LocationICAOCode]
            , GEO.[IsAirport]              AS [GEO_IsAirport]
            , GEO.[CNTRY_ID]               AS [GEO_CNTRY_ID]
            , GEO.[CountryName]            AS [GEO_CountryName]
            , GEO.[CountryISOCode]         AS [GEO_CountryISOCode]
            , GEO.[Continent]              AS [GEO_Continent]

            , CUS.[CO_ID]                  AS [CUS_CO_ID]
            , CUS.[CustomerCode]           AS [CUS_CustomerCode]
            , CUS.[CustomerICAOCode]       AS [CUS_CustomerICAOCode]
            , CUS.[CustomerName]           AS [CUS_CustomerName]
            , CUS.[CO_GRP_ID]              AS [CUS_CO_GRP_ID]
            , CUS.[GroupCode]              AS [CUS_GroupCode]
            , CUS.[GroupName]              AS [CUS_GroupName]
            , CUS.[CLIENT_ID]              AS [CUS_CLIENT_ID]
            , CUS.[ClientCode]             AS [CUS_ClientCode]
            , CUS.[ClientName]             AS [CUS_ClientName]

            , CH.[CO_ID]                   AS [CH_CO_ID]
            , CH.[ContractHolderCode]      AS [CH_ContractHolderCode]
            , CH.[ContractHolderName]      AS [CH_ContractHolderName]
            , CH.[CO_GRP_ID]               AS [CH_CO_GRP_ID]
            , CH.[GroupCode]               AS [CH_GroupCode]
            , CH.[GroupName]               AS [CH_GroupName]
            , CH.[CLIENT_ID]               AS [CH_CLIENT_ID]
            , CH.[ClientCode]              AS [CH_ClientCode]
            , CH.[ClientName]              AS [CH_ClientName]

            , SUP.[CO_ID]                  AS [SUP_CO_ID]
            , SUP.[SupplierCode]           AS [SUP_SupplierCode]
            , SUP.[SupplierName]           AS [SUP_SupplierName]
            , SUP.[SupplierCode2]          AS [SUP_SupplierCode2]
            , SUP.[SupplierCode3]          AS [SUP_SupplierCode3]

        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_SupplierVolumes]       SV
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Calendar]   CAL ON CAL.[Date]     = SV.[Month]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography]  GEO ON GEO.[LOC_ID]   = SV.[LOC_ID]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Customer]   CUS ON CUS.[CO_ID]    = SV.[CUST_CO_ID]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_ContractHolder] CH  ON CH.[CO_ID] = SV.[HLDR_CO_ID]
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Supplier]   SUP ON SUP.[CO_ID]    = SV.[CNTPRTY_CO_ID];
    END
END