CREATE                         PROCEDURE [fpx].[usp_payment_vs_due]
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID('[fpx].[Report_Payment_Vs_Due]', 'U') IS NULL
    BEGIN
        CREATE TABLE [fpx].[Report_Payment_Vs_Due] AS
        SELECT
            CAST(Inv.InvoiceID AS INT) AS Inv_InvoiceID,
            CAST(Inv.CLIENT_ID AS INT) AS Inv_CLIENT_ID,
            CAST(Inv.RCV_CO_ID AS INT) AS Inv_RCV_CO_ID,
            CAST(Inv.RCV_CO_CD AS VARCHAR(50)) AS Inv_RCV_CO_CD,
            CAST(Inv.LOC_ID AS INT) AS Inv_LOC_ID,
            CAST(Inv.LOC_CD AS VARCHAR(50)) AS Inv_LOC_CD,
            CAST(Inv.CP_CO_ID AS INT) AS Inv_CP_CO_ID,
            CAST(Inv.CP_CO_CD AS VARCHAR(50)) AS Inv_CP_CO_CD,
            CAST(Inv.INV_ISSUER_ID AS INT) AS Inv_INV_ISSUER_ID,
            CAST(Inv.INV_ISSUER_CD AS VARCHAR(50)) AS Inv_INV_ISSUER_CD,
            CAST(Inv.InvoiceNo AS VARCHAR(100)) AS Inv_InvoiceNo,
            CAST(Inv.InvoiceDate AS DATE) AS Inv_InvoiceDate,
            DATEFROMPARTS(YEAR(Inv.InvoiceDate), MONTH(Inv.InvoiceDate), 1) AS Inv_InvoiceDate_Month,
            CAST(Inv.IsIPL AS CHAR(1)) AS Inv_IsIPL,
            CAST(Inv.InvoiceCategory AS VARCHAR(50)) AS Inv_InvoiceCategory,
            CAST(Inv.InvoiceType AS VARCHAR(50)) AS Inv_InvoiceType,
            CAST(Inv.InvoiceStandard AS VARCHAR(50)) AS Inv_InvoiceStandard,
            CAST(Inv.InvoiceStandardVersion AS VARCHAR(50)) AS Inv_InvoiceStandardVersion,
            CAST(Inv.DeliveryMonth AS DATE) AS Inv_DeliveryMonth,
            CAST(Inv.[Debit/Credit] AS VARCHAR(10)) AS Inv_Debit_Credit,
            CAST(Inv.InvoiceAmount AS DECIMAL(18,2)) AS Inv_InvoiceAmount,
            CAST(Inv.InvoiceCurrency AS VARCHAR(10)) AS Inv_InvoiceCurrency,
            CAST(Inv.InvoiceAmountSys AS DECIMAL(18,2)) AS Inv_InvoiceAmountSys,
            CAST(Inv.ItemsCount AS INT) AS Inv_ItemsCount,
            CAST(Inv.CreationDate AS DATE) AS Inv_CreationDate,
            CAST(Inv.InputDate AS DATE) AS Inv_InputDate,
            CAST(Inv.ClosingDate AS DATE) AS Inv_ClosingDate,
            CAST(Inv.BaselineDateSys AS DATE) AS Inv_BaselineDateSys,
            CAST(Inv.BaselineDate AS DATE) AS Inv_BaselineDate,
            CAST(Inv.DueDate AS DATE) AS Inv_DueDate,
            DATEPART(QUARTER, Inv.DueDate) AS INV_DueDate_QuarterNum,
            YEAR(Inv.DueDate) AS INV_DueYearNum,
            CONCAT(YEAR(Inv.DueDate), '-' ,'Q', DATEPART(QUARTER, Inv.DueDate)) AS INV_Due_QuarterLabel,
            CAST(Inv.DueInDays AS DECIMAL(18,2)) AS Inv_DueInDays,
            CAST(Inv.DueInCategory AS VARCHAR(50)) AS Inv_DueInCategory,
            CAST(Inv.PaymentDate AS DATE) AS Inv_PaymentDate,
            CAST(Inv.CheckDays AS DECIMAL(18,2)) AS Inv_CheckDays,
            CAST(Inv.CheckDaysCategory AS VARCHAR(50)) AS Inv_CheckDaysCategory,
            CAST(Inv.ReceivingDelayDays AS DECIMAL(18,2)) AS Inv_ReceivingDelayDays,
            CAST(Inv.ReleaseDays AS DECIMAL(18,2)) AS Inv_ReleaseDays,
            CAST(Inv.InvoiceStillOpen AS VARCHAR(10)) AS Inv_InvoiceStillOpen,
            CAST(Inv.ReleasedOnTime AS VARCHAR(10)) AS Inv_ReleasedOnTime,
            CAST(Inv.PaymentDelayDays AS INT) AS Inv_PaymentDelayDays,
            CAST(Inv.AccountingDelayDays AS DECIMAL(18,2)) AS Inv_AccountingDelayDays,
            CAST(Inv.KPI1 AS INT) AS Inv_KPI1,
            CAST(Inv.KPI2 AS INT) AS Inv_KPI2,
            CAST(Inv.KPI3 AS INT) AS Inv_KPI3,
            CAST(Inv.KPI4 AS INT) AS Inv_KPI4,
            CAST(Inv.KPI5 AS INT) AS Inv_KPI5,
            CAST(Geo.LOC_ID AS INT) AS Geo_LOC_ID,
            CAST(Geo.LocationCode AS VARCHAR(50)) AS Geo_LocationCode,
            CAST(Geo.LocationName AS VARCHAR(100)) AS Geo_LocationName,
            CAST(Geo.LocationIATACode AS VARCHAR(10)) AS Geo_LocationIATACode,
            CAST(Geo.LocationICAOCode AS VARCHAR(10)) AS Geo_LocationICAOCode,
            CAST(Geo.IsAirport AS CHAR(1)) AS Geo_IsAirport,
            CAST(Geo.IsMonopolistic AS CHAR(1)) AS Geo_IsMonopolistic,
            CAST(Geo.CNTRY_ID AS INT) AS Geo_CNTRY_ID,
            CAST(Geo.CountryName AS VARCHAR(100)) AS Geo_CountryName,
            CAST(Geo.CountryISOCode AS VARCHAR(10)) AS Geo_CountryISOCode,
            CAST(Geo.Continent AS VARCHAR(50)) AS Geo_Continent,
            CAST(Geo.StateCode AS VARCHAR(10)) AS Geo_StateCode,
            CAST(Geo.StateName AS VARCHAR(100)) AS Geo_StateName,
            CAST(IID.InvoiceItemID AS INT) AS IID_InvoiceItemID,
            CAST(IID.InvoiceID AS INT) AS IID_InvoiceID,
            CAST(IID.QuantityDiscrepancyCount AS INT) AS IID_QuantityDiscrepancyCount,
            CAST(IID.AmountDiscrepancyCount AS INT) AS IID_AmountDiscrepancyCount,
            CAST(IID.VATDiscrepancyCount AS INT) AS IID_VATDiscrepancyCount,
            CAST(IID.QuantityInvoiced AS DECIMAL(18,2)) AS IID_QuantityInvoiced,
            CAST(IID.QuantityExpected AS DECIMAL(18,2)) AS IID_QuantityExpected,
            CAST(IID.QuantityDifference AS DECIMAL(18,2)) AS IID_QuantityDifference,
            CAST(IID.QuantityDifferenceAsAmount AS DECIMAL(18,2)) AS IID_QuantityDifferenceAsAmount,
            CAST(IID.AmountInvoiced AS DECIMAL(18,2)) AS IID_AmountInvoiced,
            CAST(IID.AmountExpected AS DECIMAL(18,2)) AS IID_AmountExpected,
            CAST(IID.AmountDifference AS DECIMAL(18,2)) AS IID_AmountDifference,
            CAST(IID.VATInvoiced AS DECIMAL(18,2)) AS IID_VATInvoiced,
            CAST(IID.VATExpected AS DECIMAL(18,2)) AS IID_VATExpected,
            CAST(IID.VATDifference AS DECIMAL(18,2)) AS IID_VATDifference,
            CAST(Cal.Date AS DATE) AS Cal_Date,
            CAST(Cal.CRT_DT AS DATE) AS Cal_CRT_DT,
            CAST(Cal.DOW AS INT) AS Cal_DOW,
            CAST(Cal.YR AS INT) AS Cal_YR,
            CAST(Cal.QT AS INT) AS Cal_QT,
            CAST(Cal.MTH AS INT) AS Cal_MTH,
            CAST(Cal.Y2D AS INT) AS Cal_Y2D,
            CAST(Cal.Q2D AS INT) AS Cal_Q2D,
            CAST(Cal.M2D AS INT) AS Cal_M2D,
            CAST(Cal.W2D AS INT) AS Cal_W2D,
            CAST(Cal.ANY_Y2D AS INT) AS Cal_ANY_Y2D,
            CAST(Cal.ANY_Q2D AS INT) AS Cal_ANY_Q2D,
            CAST(Cal.SAME_Q2D AS INT) AS Cal_SAME_Q2D,
            CAST(Cal.ANY_M2D AS INT) AS Cal_ANY_M2D,
            CAST(Cal.SAME_M2D AS INT) AS Cal_SAME_M2D,
            CAST(InvIssuer.INV_ISSUER_ID AS INT) AS InvIssuer_INV_ISSUER_ID,
            CAST(InvIssuer.InvoiceIssuerCode AS VARCHAR(50)) AS InvIssuer_InvoiceIssuerCode,
            CAST(InvIssuer.InvoiceIssuerName AS VARCHAR(100)) AS InvIssuer_InvoiceIssuerName,
            CAST(InvIssuer.CLIENT_ID AS INT) AS InvIssuer_CLIENT_ID,
            CAST(InvIssuer.ClientCode AS VARCHAR(50)) AS InvIssuer_ClientCode,
            CAST(InvIssuer.ClientName AS VARCHAR(100)) AS InvIssuer_ClientName,
            CAST(InvIssuer.CO_ID AS INT) AS InvIssuer_CO_ID,
            CAST(InvIssuer.CounterpartyCode AS VARCHAR(50)) AS InvIssuer_CounterpartyCode,
            CAST(InvIssuer.CounterpartyName AS VARCHAR(100)) AS InvIssuer_CounterpartyName,
            CAST(InvRec.CO_ID AS INT) AS InvRec_CO_ID,
            CAST(InvRec.InvoiceReceiverCode AS VARCHAR(50)) AS InvRec_InvoiceReceiverCode,
            CAST(InvRec.InvoiceReceiverName AS VARCHAR(100)) AS InvRec_InvoiceReceiverName,
            CAST(InvRec.CLIENT_ID AS INT) AS InvRec_CLIENT_ID,
            CAST(InvRec.ClientCode AS VARCHAR(50)) AS InvRec_ClientCode,
            CAST(InvRec.ClientName AS VARCHAR(100)) AS InvRec_ClientName,
            CAST(InvCP.CO_ID AS INT) AS InvCP_CO_ID,
            CAST(InvCP.CounterpartyCode AS VARCHAR(50)) AS InvCP_CounterpartyCode,
            CAST(InvCP.CounterpartyName AS VARCHAR(100)) AS InvCP_CounterpartyName,
            CAST(ClAccess.LoginName AS VARCHAR(100)) AS ClAccess_LoginName,
            CAST(ClAccess.CLIENT_ID AS INT) AS ClAccess_CLIENT_ID,
            CAST(ClAccess.ClientCode AS VARCHAR(50)) AS ClAccess_ClientCode,
            CAST(ClAccess.ClientName AS VARCHAR(100)) AS ClAccess_ClientName
        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_Invoice] Inv
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography] Geo ON Inv.LOC_ID = Geo.LOC_ID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLF_InvoiceItemDiscrepancy] IID ON Inv.InvoiceID = IID.InvoiceID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Calendar] Cal ON Cal.Date = Inv.InvoiceDate
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_InvoiceIssuer] InvIssuer ON InvIssuer.CO_ID = Inv.CP_CO_ID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_InvoiceReceiver] InvRec ON InvRec.CO_ID = Inv.CP_CO_ID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Counterparty] InvCP ON InvCP.CO_ID = Inv.CP_CO_ID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_ClientAccess] ClAccess ON ClAccess.CLIENT_ID = Inv.CLIENT_ID;
    END
    ELSE
    BEGIN
        TRUNCATE TABLE [fpx].[Report_Payment_Vs_Due];

        INSERT INTO [fpx].[Report_Payment_Vs_Due]
        SELECT
            CAST(Inv.InvoiceID AS INT) AS Inv_InvoiceID,
            CAST(Inv.CLIENT_ID AS INT) AS Inv_CLIENT_ID,
            CAST(Inv.RCV_CO_ID AS INT) AS Inv_RCV_CO_ID,
            CAST(Inv.RCV_CO_CD AS VARCHAR(50)) AS Inv_RCV_CO_CD,
            CAST(Inv.LOC_ID AS INT) AS Inv_LOC_ID,
            CAST(Inv.LOC_CD AS VARCHAR(50)) AS Inv_LOC_CD,
            CAST(Inv.CP_CO_ID AS INT) AS Inv_CP_CO_ID,
            CAST(Inv.CP_CO_CD AS VARCHAR(50)) AS Inv_CP_CO_CD,
            CAST(Inv.INV_ISSUER_ID AS INT) AS Inv_INV_ISSUER_ID,
            CAST(Inv.INV_ISSUER_CD AS VARCHAR(50)) AS Inv_INV_ISSUER_CD,
            CAST(Inv.InvoiceNo AS VARCHAR(100)) AS Inv_InvoiceNo,
            CAST(Inv.InvoiceDate AS DATE) AS Inv_InvoiceDate,
            DATEFROMPARTS(YEAR(Inv.InvoiceDate), MONTH(Inv.InvoiceDate), 1) AS Inv_InvoiceDate_Month,
            CAST(Inv.IsIPL AS CHAR(1)) AS Inv_IsIPL,
            CAST(Inv.InvoiceCategory AS VARCHAR(50)) AS Inv_InvoiceCategory,
            CAST(Inv.InvoiceType AS VARCHAR(50)) AS Inv_InvoiceType,
            CAST(Inv.InvoiceStandard AS VARCHAR(50)) AS Inv_InvoiceStandard,
            CAST(Inv.InvoiceStandardVersion AS VARCHAR(50)) AS Inv_InvoiceStandardVersion,
            CAST(Inv.DeliveryMonth AS DATE) AS Inv_DeliveryMonth,
            CAST(Inv.[Debit/Credit] AS VARCHAR(10)) AS Inv_Debit_Credit,
            CAST(Inv.InvoiceAmount AS DECIMAL(18,2)) AS Inv_InvoiceAmount,
            CAST(Inv.InvoiceCurrency AS VARCHAR(10)) AS Inv_InvoiceCurrency,
            CAST(Inv.InvoiceAmountSys AS DECIMAL(18,2)) AS Inv_InvoiceAmountSys,
            CAST(Inv.ItemsCount AS INT) AS Inv_ItemsCount,
            CAST(Inv.CreationDate AS DATE) AS Inv_CreationDate,
            CAST(Inv.InputDate AS DATE) AS Inv_InputDate,
            CAST(Inv.ClosingDate AS DATE) AS Inv_ClosingDate,
            CAST(Inv.BaselineDateSys AS DATE) AS Inv_BaselineDateSys,
            CAST(Inv.BaselineDate AS DATE) AS Inv_BaselineDate,
            CAST(Inv.DueDate AS DATE) AS Inv_DueDate,
            DATEPART(QUARTER, Inv.DueDate) AS INV_DueDate_QuarterNum,
            YEAR(Inv.DueDate) AS INV_DueYearNum,
            CONCAT(YEAR(Inv.DueDate), '-' ,'Q', DATEPART(QUARTER, Inv.DueDate)) AS INV_Due_QuarterLabel,
            CAST(Inv.DueInDays AS DECIMAL(18,2)) AS Inv_DueInDays,
            CAST(Inv.DueInCategory AS VARCHAR(50)) AS Inv_DueInCategory,
            CAST(Inv.PaymentDate AS DATE) AS Inv_PaymentDate,
            CAST(Inv.CheckDays AS DECIMAL(18,2)) AS Inv_CheckDays,
            CAST(Inv.CheckDaysCategory AS VARCHAR(50)) AS Inv_CheckDaysCategory,
            CAST(Inv.ReceivingDelayDays AS DECIMAL(18,2)) AS Inv_ReceivingDelayDays,
            CAST(Inv.ReleaseDays AS DECIMAL(18,2)) AS Inv_ReleaseDays,
            CAST(Inv.InvoiceStillOpen AS VARCHAR(10)) AS Inv_InvoiceStillOpen,
            CAST(Inv.ReleasedOnTime AS VARCHAR(10)) AS Inv_ReleasedOnTime,
            CAST(Inv.PaymentDelayDays AS INT) AS Inv_PaymentDelayDays,
            CAST(Inv.AccountingDelayDays AS DECIMAL(18,2)) AS Inv_AccountingDelayDays,
            CAST(Inv.KPI1 AS INT) AS Inv_KPI1,
            CAST(Inv.KPI2 AS INT) AS Inv_KPI2,
            CAST(Inv.KPI3 AS INT) AS Inv_KPI3,
            CAST(Inv.KPI4 AS INT) AS Inv_KPI4,
            CAST(Inv.KPI5 AS INT) AS Inv_KPI5,
            CAST(Geo.LOC_ID AS INT) AS Geo_LOC_ID,
            CAST(Geo.LocationCode AS VARCHAR(50)) AS Geo_LocationCode,
            CAST(Geo.LocationName AS VARCHAR(100)) AS Geo_LocationName,
            CAST(Geo.LocationIATACode AS VARCHAR(10)) AS Geo_LocationIATACode,
            CAST(Geo.LocationICAOCode AS VARCHAR(10)) AS Geo_LocationICAOCode,
            CAST(Geo.IsAirport AS CHAR(1)) AS Geo_IsAirport,
            CAST(Geo.IsMonopolistic AS CHAR(1)) AS Geo_IsMonopolistic,
            CAST(Geo.CNTRY_ID AS INT) AS Geo_CNTRY_ID,
            CAST(Geo.CountryName AS VARCHAR(100)) AS Geo_CountryName,
            CAST(Geo.CountryISOCode AS VARCHAR(10)) AS Geo_CountryISOCode,
            CAST(Geo.Continent AS VARCHAR(50)) AS Geo_Continent,
            CAST(Geo.StateCode AS VARCHAR(10)) AS Geo_StateCode,
            CAST(Geo.StateName AS VARCHAR(100)) AS Geo_StateName,
            CAST(IID.InvoiceItemID AS INT) AS IID_InvoiceItemID,
            CAST(IID.InvoiceID AS INT) AS IID_InvoiceID,
            CAST(IID.QuantityDiscrepancyCount AS INT) AS IID_QuantityDiscrepancyCount,
            CAST(IID.AmountDiscrepancyCount AS INT) AS IID_AmountDiscrepancyCount,
            CAST(IID.VATDiscrepancyCount AS INT) AS IID_VATDiscrepancyCount,
            CAST(IID.QuantityInvoiced AS DECIMAL(18,2)) AS IID_QuantityInvoiced,
            CAST(IID.QuantityExpected AS DECIMAL(18,2)) AS IID_QuantityExpected,
            CAST(IID.QuantityDifference AS DECIMAL(18,2)) AS IID_QuantityDifference,
            CAST(IID.QuantityDifferenceAsAmount AS DECIMAL(18,2)) AS IID_QuantityDifferenceAsAmount,
            CAST(IID.AmountInvoiced AS DECIMAL(18,2)) AS IID_AmountInvoiced,
            CAST(IID.AmountExpected AS DECIMAL(18,2)) AS IID_AmountExpected,
            CAST(IID.AmountDifference AS DECIMAL(18,2)) AS IID_AmountDifference,
            CAST(IID.VATInvoiced AS DECIMAL(18,2)) AS IID_VATInvoiced,
            CAST(IID.VATExpected AS DECIMAL(18,2)) AS IID_VATExpected,
            CAST(IID.VATDifference AS DECIMAL(18,2)) AS IID_VATDifference,
            CAST(Cal.Date AS DATE) AS Cal_Date,
            CAST(Cal.CRT_DT AS DATE) AS Cal_CRT_DT,
            CAST(Cal.DOW AS INT) AS Cal_DOW,
            CAST(Cal.YR AS INT) AS Cal_YR,
            CAST(Cal.QT AS INT) AS Cal_QT,
            CAST(Cal.MTH AS INT) AS Cal_MTH,
            CAST(Cal.Y2D AS INT) AS Cal_Y2D,
            CAST(Cal.Q2D AS INT) AS Cal_Q2D,
            CAST(Cal.M2D AS INT) AS Cal_M2D,
            CAST(Cal.W2D AS INT) AS Cal_W2D,
            CAST(Cal.ANY_Y2D AS INT) AS Cal_ANY_Y2D,
            CAST(Cal.ANY_Q2D AS INT) AS Cal_ANY_Q2D,
            CAST(Cal.SAME_Q2D AS INT) AS Cal_SAME_Q2D,
            CAST(Cal.ANY_M2D AS INT) AS Cal_ANY_M2D,
            CAST(Cal.SAME_M2D AS INT) AS Cal_SAME_M2D,
CAST(InvIssuer.INV_ISSUER_ID AS INT) AS InvIssuer_INV_ISSUER_ID,
CAST(InvIssuer.InvoiceIssuerCode AS VARCHAR(50)) AS InvIssuer_InvoiceIssuerCode,
CAST(InvIssuer.InvoiceIssuerName AS VARCHAR(100)) AS InvIssuer_InvoiceIssuerName,
CAST(InvIssuer.CLIENT_ID AS INT) AS InvIssuer_CLIENT_ID,
CAST(InvIssuer.ClientCode AS VARCHAR(50)) AS InvIssuer_ClientCode,
CAST(InvIssuer.ClientName AS VARCHAR(100)) AS InvIssuer_ClientName,
CAST(InvIssuer.CO_ID AS INT) AS InvIssuer_CO_ID,
CAST(InvIssuer.CounterpartyCode AS VARCHAR(50)) AS InvIssuer_CounterpartyCode,
CAST(InvIssuer.CounterpartyName AS VARCHAR(100)) AS InvIssuer_CounterpartyName,
CAST(InvRec.CO_ID AS INT) AS InvRec_CO_ID,
CAST(InvRec.InvoiceReceiverCode AS VARCHAR(50)) AS InvRec_InvoiceReceiverCode,
CAST(InvRec.InvoiceReceiverName AS VARCHAR(100)) AS InvRec_InvoiceReceiverName,
CAST(InvRec.CLIENT_ID AS INT) AS InvRec_CLIENT_ID,
CAST(InvRec.ClientCode AS VARCHAR(50)) AS InvRec_ClientCode,
CAST(InvRec.ClientName AS VARCHAR(100)) AS InvRec_ClientName,
CAST(InvCP.CO_ID AS INT) AS InvCP_CO_ID,
CAST(InvCP.CounterpartyCode AS VARCHAR(50)) AS InvCP_CounterpartyCode,
CAST(InvCP.CounterpartyName AS VARCHAR(100)) AS InvCP_CounterpartyName,
CAST(ClAccess.LoginName AS VARCHAR(100)) AS ClAccess_LoginName,
CAST(ClAccess.CLIENT_ID AS INT) AS ClAccess_CLIENT_ID,
CAST(ClAccess.ClientCode AS VARCHAR(50)) AS ClAccess_ClientCode,
CAST(ClAccess.ClientName AS VARCHAR(100)) AS ClAccess_ClientName
       FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_Invoice] Inv
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography] Geo ON Inv.LOC_ID = Geo.LOC_ID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLF_InvoiceItemDiscrepancy] IID ON Inv.InvoiceID = IID.InvoiceID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Calendar] Cal ON Cal.Date = Inv.InvoiceDate
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_InvoiceIssuer] InvIssuer ON InvIssuer.CO_ID = Inv.CP_CO_ID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_InvoiceReceiver] InvRec ON InvRec.CO_ID = Inv.CP_CO_ID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Counterparty] InvCP ON InvCP.CO_ID = Inv.CP_CO_ID
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_ClientAccess] ClAccess ON ClAccess.CLIENT_ID = Inv.CLIENT_ID;
    END
END