CREATE  PROCEDURE [fpx].[usp_actual_flights]
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID('[fpx].[Report_Actual_Flights]', 'U') IS NULL
    BEGIN
        SELECT
              AF.[FlightID]                 AS [AF_FlightID]
            , AF.[FlightDate]               AS [AF_FlightDate]
            , AF.[Registration]             AS [AF_Registration]
            , AF.[Departure]                AS [AF_Departure]
            , AF.[Destination]              AS [AF_Destination]
            , AF.[AirlineDesignator]        AS [AF_AirlineDesignator]
            , AF.[FlightNumber]             AS [AF_FlightNumber]
            , AF.[Suffix]                   AS [AF_Suffix]
            , AF.[AircraftType]             AS [AF_AircraftType]
            , AF.[Leg]                      AS [AF_Leg]
            , AF.[LegAircraftType]          AS [AF_LegAircraftType]
            , AF.[SpecialEvent]             AS [AF_SpecialEvent]
            , AF.[DomInt]                   AS [AF_DomInt]
            , AF.[DepartureDate]            AS [AF_DepartureDate]
            , AF.[OffBlockTimeUTC]          AS [AF_OffBlockTimeUTC]
            , AF.[TakeOffTimeUTC]           AS [AF_TakeOffTimeUTC]
            , AF.[TouchDownTimeUTC]         AS [AF_TouchDownTimeUTC]
            , AF.[OnBlockTimeUTC]           AS [AF_OnBlockTimeUTC]
            , AF.[BlockTime]                AS [AF_BlockTime]
            , AF.[FlightTime]               AS [AF_FlightTime]
            , AF.[Operator]                 AS [AF_Operator]
            , AF.[Owner]                    AS [AF_Owner]
            , AF.[Customer]                 AS [AF_Customer]
            , AF.[UpliftVol]                AS [AF_UpliftVol]
            , AF.[UpliftMass]               AS [AF_UpliftMass]
            , AF.[UpliftDensity]            AS [AF_UpliftDensity]
            , AF.[UpliftStatus]             AS [AF_UpliftStatus]
            , AF.[UpliftCost]               AS [AF_UpliftCost]
            , AF.[IPStatus]                 AS [AF_IPStatus]
            , AF.[BeforeFuelingVol]         AS [AF_BeforeFuelingVol]
            , AF.[BeforeFuelingMass]        AS [AF_BeforeFuelingMass]
            , AF.[OffBlockFuelVol]          AS [AF_OffBlockFuelVol]
            , AF.[OffBlockFuelMass]         AS [AF_OffBlockFuelMass]
            , AF.[ShutDownFuelVol]          AS [AF_ShutDownFuelVol]
            , AF.[ShutDownFuelMass]         AS [AF_ShutDownFuelMass]
            , AF.[FuelDumpVol]              AS [AF_FuelDumpVol]
            , AF.[FuelDumpMass]             AS [AF_FuelDumpMass]
            , AF.[BlockConsumptionVol]      AS [AF_BlockConsumptionVol]
            , AF.[BlockConsumptionMass]     AS [AF_BlockConsumptionMass]
            , AF.[BlockConsumptionStatus]   AS [AF_BlockConsumptionStatus]
            , AF.[TotalConsumptionVol]      AS [AF_TotalConsumptionVol]
            , AF.[TotalConsumptionMass]     AS [AF_TotalConsumptionMass]
            , AF.[TotalConsumptionStatus]   AS [AF_TotalConsumptionStatus]
            , AF.[BlockConsumptionCost]     AS [AF_BlockConsumptionCost]
            , AF.[TotalConsumptionCost]     AS [AF_TotalConsumptionCost]
            , AF.[APUConsumptionVol]        AS [AF_APUConsumptionVol]
            , AF.[APUConsumptionMass]       AS [AF_APUConsumptionMass]
            , AF.[APUConsumptionCost]       AS [AF_APUConsumptionCost]
            , AF.[TankeredFuelVol]          AS [AF_TankeredFuelVol]
            , AF.[TankeredFuelMass]         AS [AF_TankeredFuelMass]
            , AF.[Division]                 AS [AF_Division]
            , AF.[FlightSeqNo]              AS [AF_FlightSeqNo]
            , AF.[FlightType]               AS [AF_FlightType]
            , AF.[ServiceType]              AS [AF_ServiceType]
            , AF.[ReportedCustomer]         AS [AF_ReportedCustomer]
            , AF.[LegDistance]              AS [AF_LegDistance]

            , GEO.[LOC_ID]                  AS [GEO_LOC_ID]
            , GEO.[LocationCode]            AS [GEO_LocationCode]
            , GEO.[LocationName]            AS [GEO_LocationName]
            , GEO.[LocationIATACode]        AS [GEO_LocationIATACode]
            , GEO.[LocationICAOCode]        AS [GEO_LocationICAOCode]
            , GEO.[IsAirport]               AS [GEO_IsAirport]
            , GEO.[CNTRY_ID]                AS [GEO_CNTRY_ID]
            , GEO.[CountryName]             AS [GEO_CountryName]
            , GEO.[CountryISOCode]          AS [GEO_CountryISOCode]
            , GEO.[Continent]               AS [GEO_Continent]
            , AF.[Departure] + '-' + AF.[Destination]   AS [Route]
            , CONCAT(YEAR(AF.[DepartureDate]), '-', RIGHT('00' + CONVERT(varchar(2), MONTH(AF.[DepartureDate])), 2)) AS [AF_DepartureDate_Month]

        INTO [fpx].[Report_Actual_Flights]
        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_ActualFlights] AF
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography] GEO 
               ON AF.[Departure] = GEO.[LocationIATACode];
    END
    ELSE
    BEGIN
        TRUNCATE TABLE [fpx].[Report_Actual_Flights];

        INSERT INTO [fpx].[Report_Actual_Flights]
        SELECT
              AF.[FlightID]                 AS [AF_FlightID]
            , AF.[FlightDate]               AS [AF_FlightDate]
            , AF.[Registration]             AS [AF_Registration]
            , AF.[Departure]                AS [AF_Departure]
            , AF.[Destination]              AS [AF_Destination]
            , AF.[AirlineDesignator]        AS [AF_AirlineDesignator]
            , AF.[FlightNumber]             AS [AF_FlightNumber]
            , AF.[Suffix]                   AS [AF_Suffix]
            , AF.[AircraftType]             AS [AF_AircraftType]
            , AF.[Leg]                      AS [AF_Leg]
            , AF.[LegAircraftType]          AS [AF_LegAircraftType]
            , AF.[SpecialEvent]             AS [AF_SpecialEvent]
            , AF.[DomInt]                   AS [AF_DomInt]
            , AF.[DepartureDate]            AS [AF_DepartureDate]
            , AF.[OffBlockTimeUTC]          AS [AF_OffBlockTimeUTC]
            , AF.[TakeOffTimeUTC]           AS [AF_TakeOffTimeUTC]
            , AF.[TouchDownTimeUTC]         AS [AF_TouchDownTimeUTC]
            , AF.[OnBlockTimeUTC]           AS [AF_OnBlockTimeUTC]
            , AF.[BlockTime]                AS [AF_BlockTime]
            , AF.[FlightTime]               AS [AF_FlightTime]
            , AF.[Operator]                 AS [AF_Operator]
            , AF.[Owner]                    AS [AF_Owner]
            , AF.[Customer]                 AS [AF_Customer]
            , AF.[UpliftVol]                AS [AF_UpliftVol]
            , AF.[UpliftMass]               AS [AF_UpliftMass]
            , AF.[UpliftDensity]            AS [AF_UpliftDensity]
            , AF.[UpliftStatus]             AS [AF_UpliftStatus]
            , AF.[UpliftCost]               AS [AF_UpliftCost]
            , AF.[IPStatus]                 AS [AF_IPStatus]
            , AF.[BeforeFuelingVol]         AS [AF_BeforeFuelingVol]
            , AF.[BeforeFuelingMass]        AS [AF_BeforeFuelingMass]
            , AF.[OffBlockFuelVol]          AS [AF_OffBlockFuelVol]
            , AF.[OffBlockFuelMass]         AS [AF_OffBlockFuelMass]
            , AF.[ShutDownFuelVol]          AS [AF_ShutDownFuelVol]
            , AF.[ShutDownFuelMass]         AS [AF_ShutDownFuelMass]
            , AF.[FuelDumpVol]              AS [AF_FuelDumpVol]
            , AF.[FuelDumpMass]             AS [AF_FuelDumpMass]
            , AF.[BlockConsumptionVol]      AS [AF_BlockConsumptionVol]
            , AF.[BlockConsumptionMass]     AS [AF_BlockConsumptionMass]
            , AF.[BlockConsumptionStatus]   AS [AF_BlockConsumptionStatus]
            , AF.[TotalConsumptionVol]      AS [AF_TotalConsumptionVol]
            , AF.[TotalConsumptionMass]     AS [AF_TotalConsumptionMass]
            , AF.[TotalConsumptionStatus]   AS [AF_TotalConsumptionStatus]
            , AF.[BlockConsumptionCost]     AS [AF_BlockConsumptionCost]
            , AF.[TotalConsumptionCost]     AS [AF_TotalConsumptionCost]
            , AF.[APUConsumptionVol]        AS [AF_APUConsumptionVol]
            , AF.[APUConsumptionMass]       AS [AF_APUConsumptionMass]
            , AF.[APUConsumptionCost]       AS [AF_APUConsumptionCost]
            , AF.[TankeredFuelVol]          AS [AF_TankeredFuelVol]
            , AF.[TankeredFuelMass]         AS [AF_TankeredFuelMass]
            , AF.[Division]                 AS [AF_Division]
            , AF.[FlightSeqNo]              AS [AF_FlightSeqNo]
            , AF.[FlightType]               AS [AF_FlightType]
            , AF.[ServiceType]              AS [AF_ServiceType]
            , AF.[ReportedCustomer]         AS [AF_ReportedCustomer]
            , AF.[LegDistance]              AS [AF_LegDistance]

            , GEO.[LOC_ID]                  AS [GEO_LOC_ID]
            , GEO.[LocationCode]            AS [GEO_LocationCode]
            , GEO.[LocationName]            AS [GEO_LocationName]
            , GEO.[LocationIATACode]        AS [GEO_LocationIATACode]
            , GEO.[LocationICAOCode]        AS [GEO_LocationICAOCode]
            , GEO.[IsAirport]               AS [GEO_IsAirport]
            , GEO.[CNTRY_ID]                AS [GEO_CNTRY_ID]
            , GEO.[CountryName]             AS [GEO_CountryName]
            , GEO.[CountryISOCode]          AS [GEO_CountryISOCode]
            , GEO.[Continent]               AS [GEO_Continent]
            , AF.[Departure] + '-' + AF.[Destination]   AS [Route]
            , CONCAT(YEAR(AF.[DepartureDate]), '-', RIGHT('00' + CONVERT(varchar(2), MONTH(AF.[DepartureDate])), 2)) AS [AF_DepartureDate_Month]

        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_ActualFlights] AF
        LEFT OUTER JOIN [LH_ATGIQ].[fpx_raw].[V_ANLD_Geography] GEO 
               ON AF.[Departure] = GEO.[LocationIATACode];
    END
END