CREATE               PROCEDURE [fpx].[usp_Load_Fact_Invoice]
AS
BEGIN
    SET NOCOUNT ON;


    IF NOT EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'fpx'
          AND TABLE_NAME = 'Fact_Invoice'
          AND TABLE_CATALOG = 'WH_ATGIQ'
    )
    BEGIN
    
            CREATE TABLE fpx.Fact_Invoice AS
			SELECT [InvoiceID],
			[CLIENT_ID],
			[RCV_CO_ID],
			[RCV_CO_CD],
			[LOC_ID],
			[LOC_CD],
			[AccountingDelayDays],
			[KPI1],
			[KPI2],
			[KPI3],
			[KPI4],
			[KPI5],
			[CheckDaysCategory],
			[ReceivingDelayDays],
			[ReleaseDays],
			[InvoiceStillOpen],
			[ReleasedOnTime],
			[PaymentDelayDays],
			[BaselineDate],
			[DueDate],
			[DueInDays],
			[DueInCategory],
			[PaymentDate],
			[CheckDays],
			[InvoiceQuantitySys],
			[ItemsCount],
			[CreationDate],
			[InputDate],
			[ClosingDate],
			[BaselineDateSys],
			[Debit/Credit],
			[InvoiceAmount],
			[InvoiceCurrency],
			[InvoiceAmountSys],
			[InvoiceQuantity],
			[InvoiceUnit],
			[IsIPL],
			[InvoiceCategory],
			[InvoiceType],
			[InvoiceStandard],
			[InvoiceStandardVersion],
			[DeliveryMonth],
			[CP_CO_ID],
			[CP_CO_CD],
			[INV_ISSUER_ID],
			[INV_ISSUER_CD],
			[InvoiceNo],
			[InvoiceDate]
FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_Invoice]
    END
    ELSE
    BEGIN

        TRUNCATE TABLE [fpx].[Fact_Invoice];
 
 
    INSERT INTO [WH_ATGIQ].[fpx].[Fact_Invoice] (
 			[InvoiceID],
			[CLIENT_ID],
			[RCV_CO_ID],
			[RCV_CO_CD],
			[LOC_ID],
			[LOC_CD],
			[AccountingDelayDays],
			[KPI1],
			[KPI2],
			[KPI3],
			[KPI4],
			[KPI5],
			[CheckDaysCategory],
			[ReceivingDelayDays],
			[ReleaseDays],
			[InvoiceStillOpen],
			[ReleasedOnTime],
			[PaymentDelayDays],
			[BaselineDate],
			[DueDate],
			[DueInDays],
			[DueInCategory],
			[PaymentDate],
			[CheckDays],
			[InvoiceQuantitySys],
			[ItemsCount],
			[CreationDate],
			[InputDate],
			[ClosingDate],
			[BaselineDateSys],
			[Debit/Credit],
			[InvoiceAmount],
			[InvoiceCurrency],
			[InvoiceAmountSys],
			[InvoiceQuantity],
			[InvoiceUnit],
			[IsIPL],
			[InvoiceCategory],
			[InvoiceType],
			[InvoiceStandard],
			[InvoiceStandardVersion],
			[DeliveryMonth],
			[CP_CO_ID],
			[CP_CO_CD],
			[INV_ISSUER_ID],
			[INV_ISSUER_CD],
			[InvoiceNo],
			[InvoiceDate]
			)
			SELECT [InvoiceID],
			[CLIENT_ID],
			[RCV_CO_ID],
			[RCV_CO_CD],
			[LOC_ID],
			[LOC_CD],
			[AccountingDelayDays],
			[KPI1],
			[KPI2],
			[KPI3],
			[KPI4],
			[KPI5],
			[CheckDaysCategory],
			[ReceivingDelayDays],
			[ReleaseDays],
			[InvoiceStillOpen],
			[ReleasedOnTime],
			[PaymentDelayDays],
			[BaselineDate],
			[DueDate],
			[DueInDays],
			[DueInCategory],
			[PaymentDate],
			[CheckDays],
			[InvoiceQuantitySys],
			[ItemsCount],
			[CreationDate],
			[InputDate],
			[ClosingDate],
			[BaselineDateSys],
			[Debit/Credit],
			[InvoiceAmount],
			[InvoiceCurrency],
			[InvoiceAmountSys],
			[InvoiceQuantity],
			[InvoiceUnit],
			[IsIPL],
			[InvoiceCategory],
			[InvoiceType],
			[InvoiceStandard],
			[InvoiceStandardVersion],
			[DeliveryMonth],
			[CP_CO_ID],
			[CP_CO_CD],
			[INV_ISSUER_ID],
			[INV_ISSUER_CD],
			[InvoiceNo],
			[InvoiceDate]
FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_Invoice]
END
END