CREATE           PROCEDURE [fpx].[usp_Load_Fact_ForecastVsActual]
AS
BEGIN
    SET NOCOUNT ON;


    IF NOT EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'fpx'
          AND TABLE_NAME = 'Fact_ForecastVsActual'
          AND TABLE_CATALOG = 'WH_ATGIQ'
    )
    BEGIN
    
            CREATE TABLE fpx.Fact_ForecastVsActual AS
            SELECT [FlightDate],
			[Departure],
			[Destination],
			[AircraftType],
			[AirlineDesignator],
			[FlightNumber],
			[TotalConsumPriceVariancePrcOT],
			[TotalConsumVariancePrcOT],
			[UpliftCostVariancePrcOT],
			[BlockConsumCostVariancePrcOT],
			[TotalConsumCostVariancePrcOT],
			[UpliftPriceVariancePrcOT],
			[BlockConsumPriceVariancePrcOT],
			[TotalConsumCostVariancePrc],
			[UpliftPriceVariancePrc],
			[BlockConsumPriceVariancePrc],
			[TotalConsumPriceVariancePrc],
			[UpliftVariancePrcOT],
			[BlockConsumVariancePrcOT],
			[Matched],
			[UpliftVariancePrc],
			[BlockConsumVariancePrc],
			[TotalConsumVariancePrc],
			[UpliftCostVariancePrc],
			[BlockConsumCostVariancePrc],
			[BlockTimePlanned],
			[BlockTimeActual],
			[BlockTimevariance],
			[UpliftStatusActual],
			[BlockConsumptionStatusActual],
			[TotalConsumptionStatusActual],
			[BlockConsumptionPriceVariance],
			[TotalConsumptionPriceActual],
			[TotalConsumptionPriceVariance],
			[CO2EmissionPlanned],
			[CO2EmissionActual],
			[CO2EmissionVariance],
			[TotalConsumptionCostActual],
			[TotalConsumptionCostVariance],
			[PricePlanned],
			[UpliftPriceActual],
			[UpliftPriceVariance],
			[BlockConsumptionPriceActual],
			[TotalConsumptionVariance],
			[CostPlanned],
			[UpliftCostActual],
			[UpliftCostVariance],
			[BlockConsumptionCostActual],
			[BlockConsumptionCostVariance],
			[QuantityPlanned],
			[UpliftActual],
			[UpliftVariance],
			[BlockConsumptionActual],
			[BlockConsumptionVariance],
			[TotalConsumptionActual],
			[Suffix],
			[Leg],
			[LegAircraftType],
			[FrequencyPlanned],
			[FrequencyActual],
			[FrequencyVariance]
        FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_ForecastVsActual]
    END
    ELSE
    BEGIN

        TRUNCATE TABLE [fpx].[Fact_ForecastVsActual];
    END

   
    INSERT INTO [WH_ATGIQ].[fpx].[Fact_ForecastVsActual] (
    [FlightDate],
			[Departure],
			[Destination],
			[AircraftType],
			[AirlineDesignator],
			[FlightNumber],
			[TotalConsumPriceVariancePrcOT],
			[TotalConsumVariancePrcOT],
			[UpliftCostVariancePrcOT],
			[BlockConsumCostVariancePrcOT],
			[TotalConsumCostVariancePrcOT],
			[UpliftPriceVariancePrcOT],
			[BlockConsumPriceVariancePrcOT],
			[TotalConsumCostVariancePrc],
			[UpliftPriceVariancePrc],
			[BlockConsumPriceVariancePrc],
			[TotalConsumPriceVariancePrc],
			[UpliftVariancePrcOT],
			[BlockConsumVariancePrcOT],
			[Matched],
			[UpliftVariancePrc],
			[BlockConsumVariancePrc],
			[TotalConsumVariancePrc],
			[UpliftCostVariancePrc],
			[BlockConsumCostVariancePrc],
			[BlockTimePlanned],
			[BlockTimeActual],
			[BlockTimevariance],
			[UpliftStatusActual],
			[BlockConsumptionStatusActual],
			[TotalConsumptionStatusActual],
			[BlockConsumptionPriceVariance],
			[TotalConsumptionPriceActual],
			[TotalConsumptionPriceVariance],
			[CO2EmissionPlanned],
			[CO2EmissionActual],
			[CO2EmissionVariance],
			[TotalConsumptionCostActual],
			[TotalConsumptionCostVariance],
			[PricePlanned],
			[UpliftPriceActual],
			[UpliftPriceVariance],
			[BlockConsumptionPriceActual],
			[TotalConsumptionVariance],
			[CostPlanned],
			[UpliftCostActual],
			[UpliftCostVariance],
			[BlockConsumptionCostActual],
			[BlockConsumptionCostVariance],
			[QuantityPlanned],
			[UpliftActual],
			[UpliftVariance],
			[BlockConsumptionActual],
			[BlockConsumptionVariance],
			[TotalConsumptionActual],
			[Suffix],
			[Leg],
			[LegAircraftType],
			[FrequencyPlanned],
			[FrequencyActual],
			[FrequencyVariance]
    )
   SELECT [FlightDate],
			[Departure],
			[Destination],
			[AircraftType],
			[AirlineDesignator],
			[FlightNumber],
			[TotalConsumPriceVariancePrcOT],
			[TotalConsumVariancePrcOT],
			[UpliftCostVariancePrcOT],
			[BlockConsumCostVariancePrcOT],
			[TotalConsumCostVariancePrcOT],
			[UpliftPriceVariancePrcOT],
			[BlockConsumPriceVariancePrcOT],
			[TotalConsumCostVariancePrc],
			[UpliftPriceVariancePrc],
			[BlockConsumPriceVariancePrc],
			[TotalConsumPriceVariancePrc],
			[UpliftVariancePrcOT],
			[BlockConsumVariancePrcOT],
			[Matched],
			[UpliftVariancePrc],
			[BlockConsumVariancePrc],
			[TotalConsumVariancePrc],
			[UpliftCostVariancePrc],
			[BlockConsumCostVariancePrc],
			[BlockTimePlanned],
			[BlockTimeActual],
			[BlockTimevariance],
			[UpliftStatusActual],
			[BlockConsumptionStatusActual],
			[TotalConsumptionStatusActual],
			[BlockConsumptionPriceVariance],
			[TotalConsumptionPriceActual],
			[TotalConsumptionPriceVariance],
			[CO2EmissionPlanned],
			[CO2EmissionActual],
			[CO2EmissionVariance],
			[TotalConsumptionCostActual],
			[TotalConsumptionCostVariance],
			[PricePlanned],
			[UpliftPriceActual],
			[UpliftPriceVariance],
			[BlockConsumptionPriceActual],
			[TotalConsumptionVariance],
			[CostPlanned],
			[UpliftCostActual],
			[UpliftCostVariance],
			[BlockConsumptionCostActual],
			[BlockConsumptionCostVariance],
			[QuantityPlanned],
			[UpliftActual],
			[UpliftVariance],
			[BlockConsumptionActual],
			[BlockConsumptionVariance],
			[TotalConsumptionActual],
			[Suffix],
			[Leg],
			[LegAircraftType],
			[FrequencyPlanned],
			[FrequencyActual],
			[FrequencyVariance]
FROM [LH_ATGIQ].[fpx_raw].[V_ANLF_ForecastVsActual];
END