CREATE TABLE [fpx].[Fact_ForecastFlights] (

	[FlightDate] datetime2(6) NULL, 
	[Departure] varchar(8000) NULL, 
	[Destination] varchar(8000) NULL, 
	[AirlineDesignator] varchar(8000) NULL, 
	[FlightNumber] varchar(8000) NULL, 
	[Suffix] varchar(8000) NULL, 
	[AircraftType] varchar(8000) NULL, 
	[Leg] varchar(8000) NULL, 
	[LegAircraftType] varchar(8000) NULL, 
	[Frequency] float NULL, 
	[StatisticalUplift] float NULL, 
	[StatisticalConsumption] float NULL, 
	[TheoreticalConsumption] float NULL, 
	[PriceUplift] float NULL, 
	[PriceStatisticalConsumption] float NULL, 
	[PriceTheoreticalConsumption] float NULL, 
	[CostUplift] float NULL, 
	[CostStatisticalConsumption] float NULL, 
	[CostTheoreticalConsumption] float NULL, 
	[StandardConsumption] float NULL, 
	[CO2Emission] float NULL, 
	[Division] varchar(8000) NULL, 
	[CustomerICAOCode] varchar(8000) NULL, 
	[DomInt] varchar(8000) NULL, 
	[BlockHours] float NULL
);