CREATE TABLE [fpx].[Report_Billback] (

	[InvoiceID] decimal(10,0) NULL, 
	[InvoiceLevel] varchar(8000) NULL, 
	[CLIENT_ID] decimal(10,0) NULL, 
	[CNTPRTY_CO_ID] decimal(10,0) NULL, 
	[INV_ISSUER_ID] decimal(10,0) NULL, 
	[RCV_CO_ID] decimal(10,0) NULL, 
	[LOC_ID] decimal(10,0) NULL, 
	[IsIPL] varchar(8000) NULL, 
	[InvoiceNo] varchar(8000) NULL, 
	[InvoiceDate] datetime2(6) NULL, 
	[InputDate] datetime2(6) NULL, 
	[ApprovalDate] datetime2(6) NULL, 
	[DueDate] datetime2(6) NULL, 
	[DeliveryFrom] datetime2(6) NULL, 
	[DeliveryTo] datetime2(6) NULL, 
	[InvoiceType] varchar(8000) NULL, 
	[InvoiceCategory] varchar(8000) NULL, 
	[InvoiceStatus] varchar(8000) NULL, 
	[ItemsCount] float NULL, 
	[InvoiceAmount] float NULL, 
	[InvoiceCurrency] varchar(8000) NULL, 
	[InvoiceAmountSys] float NULL, 
	[QuantitySys] float NULL, 
	[CounterpartyAgreement] varchar(8000) NULL, 
	[TransactionType] varchar(8000) NULL, 
	[CounterpartyCode] varchar(8000) NULL, 
	[CounterpartyName] varchar(8000) NULL
);